apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabnik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabnik
  template:
    metadata:
      labels:
        app: uporabnik
    spec:
      containers:
        - image: corurban/uporabnik:2024-01-08-12-25-23
          name: uporabnik
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-twilight-meadow-75165427.eu-central-1.aws.neon.tech/katalog-destinacij-db
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: urbi.cor
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: XW6sdZnq3jpH
              #valueFrom: #use Kubernetes secret for storing the password
                #secretKeyRef:
                  #name: #to be added
                  #key: #to be added
          ports:
            - containerPort: 8083
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: uporabnik-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: uporabnik
