kumuluzee:
  name: uporabnik-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/UporabnikDS
      connection-url: jdbc:postgresql://ep-ancient-fog-19741782-pooler.eu-central-1.aws.neon.tech/izletnik
      username: grzin
      password: ep2sMLqtu3rk
  openapi-mp:
    ui:
      specification-server: http://localhost:8083
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UporabnikDS
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/uporabnik/*
rest-properties:
  broken: false

