kumuluzee:
  name: uporabnik-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/UporabnikDS
      connection-url: jdbc:postgresql://ep-twilight-meadow-75165427.eu-central-1.aws.neon.tech/katalog-destinacij-db
      username: urbi.cor
      password: XW6sdZnq3jpH
  openapi-mp:
    ui:
      specification-server: http://localhost:8083
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UporabnikDS
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/uporabnik/*
  cors:
    enabled: true
    paths: "/*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    max-age: 3600
    credentials: false
    allowed-origin: "*"
rest-properties:
  broken: false

