kumuluzee:
  name: uporabnik-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/UporabnikDS
      connection-url: jdbc:postgresql://ep-twilight-meadow-75165427.eu-central-1.aws.neon.tech/katalog-destinacij-db
      username: urbi.cor
      password: XW6sdZnq3jpH
  openapi-mp:
    enabled: true
    servlet:
      mapping: /v1/uporabnik/openapi
    ui:
      specification-server: http://localhost:8083
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UporabnikDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="f4e5773d-c9f5-4519-9c8d-495ce795f5be-ls.logit.io"
                                      port="22241" protocol="udp">
                                          <JSONLayout complete="false " compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'
  metrics:
    web-instrumentation:
      - name: destinacije-endpoint
        url-pattern: /v1/uporabnik/*
  cors:
    enabled: true
    paths: "/*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    max-age: 3600
    credentials: false
    allowed-origin: "*"
rest-properties:
  broken: false

