name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timezone: 1
          format: 'YYYY-MM-DD-hh-mm-ss'

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_with_maven_build
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rso_uporabnik:${{ steps.time.outputs.time }}
